"""empty message

Revision ID: 80ce00227345
Revises: 857efef60fd6
Create Date: 2017-05-31 16:05:59.585790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ce00227345'
down_revision = '857efef60fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huntlocation', sa.Column('location_order', sa.Integer(), nullable=False))
    op.drop_column('huntlocation', 'order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huntlocation', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('huntlocation', 'location_order')
    # ### end Alembic commands ###
