"""empty message

Revision ID: 823658494b39
Revises: 65d24dfde817
Create Date: 2017-05-31 14:12:18.048998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823658494b39'
down_revision = '65d24dfde817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hunt_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hunt_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hunt_id'], ['hunts.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('locations_hunt_id_fkey', 'locations', type_='foreignkey')
    op.drop_column('locations', 'hunt_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('hunt_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('locations_hunt_id_fkey', 'locations', 'hunts', ['hunt_id'], ['id'], ondelete='CASCADE')
    op.drop_table('hunt_map')
    # ### end Alembic commands ###
