"""empty message

Revision ID: 857efef60fd6
Revises: a09e941336aa
Create Date: 2017-05-31 14:52:22.796881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857efef60fd6'
down_revision = 'a09e941336aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huntlocation', sa.Column('order', sa.Integer(), nullable=False))
    op.drop_column('locations', 'order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('huntlocation', 'order')
    # ### end Alembic commands ###
