"""empty message

Revision ID: d46efe833c01
Revises: 80ce00227345
Create Date: 2017-06-02 11:10:55.184554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46efe833c01'
down_revision = '80ce00227345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huntlocation', sa.Column('hint', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('huntlocation', 'hint')
    # ### end Alembic commands ###
