"""empty message

Revision ID: dd86d08ba900
Revises: d6bd3892da7f
Create Date: 2017-05-30 15:05:37.562143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd86d08ba900'
down_revision = 'd6bd3892da7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hunts_user_id_fkey', 'hunts', type_='foreignkey')
    op.create_foreign_key(None, 'hunts', 'users', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hunts', type_='foreignkey')
    op.create_foreign_key('hunts_user_id_fkey', 'hunts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
